[project]
name = 'smart-contracts'
description = ''
authors = []
telemetry = false
cache_dir = './.cache'

[[project.requirements]]
contract_id = 'ST3VRQJMS69354J6DTPKG5W67XP31D4E6HJW708W4.Wrapped-Bitcoin'
[contracts.Wrapped-Bitcoin]
path = 'contracts/Wrapped-Bitcoin.clar'
clarity_version = 2
epoch = 2.1

[contracts.alex-vault-v1-1]
path = 'contracts/alex-vault-v1-1.clar'
clarity_version = 2
epoch = 2.1

[contracts.amm-swap-pool-v1-1]
path = 'contracts/amm-swap-pool-v1-1.clar'
clarity_version = 2
epoch = 2.1

[contracts.bridge]
path = 'contracts/bridge.clar'
clarity_version = 2
epoch = 2.1

[contracts.bridge-contract]
path = 'contracts/bridge-contract.clar'
clarity_version = 2
epoch = 2.1

[contracts.clarity-bitcoin]
path = 'contracts/clarity-bitcoin.clar'
clarity_version = 2
epoch = 2.1

[contracts.ft-trait]
path = 'contracts/ft-trait.clar'
clarity_version = 2
epoch = 2.1

[contracts.restricted-token-trait]
path = 'contracts/restricted-token-trait.clar'
clarity_version = 2
epoch = 2.1

[contracts.token-amm-swap-pool-v1-1]
path = 'contracts/token-amm-swap-pool-v1-1.clar'
clarity_version = 2
epoch = 2.1

[contracts.token-wbtc]
path = 'contracts/token-wbtc.clar'
clarity_version = 2
epoch = 2.1

[contracts.token-wstx]
path = 'contracts/token-wstx.clar'
clarity_version = 2
epoch = 2.1

[contracts.trait-flash-loan-user]
path = 'contracts/trait-flash-loan-user.clar'
clarity_version = 2
epoch = 2.1

[contracts.trait-ownable]
path = 'contracts/trait-ownable.clar'
clarity_version = 2
epoch = 2.1

[contracts.trait-semi-fungible]
path = 'contracts/trait-semi-fungible.clar'
clarity_version = 2
epoch = 2.1

[contracts.trait-sip-010]
path = 'contracts/trait-sip-010.clar'
clarity_version = 2
epoch = 2.1
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
